import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

/**
 * Validates stress thresholds and manages Google Calendar defense mechanisms.
 */
export async function processCalendarAction(userId: string, stressScore: number) {
  // Fetch user preferences and confidence scores
  const { data: user } = await supabase
    .from('users')
    .select('stress_threshold')
    .eq('id', userId)
    .single();

  const threshold = user?.stress_threshold || 80;
  const confidenceScore = calculateConfidence(stressScore); // Mock function for payload quality

  if (stressScore < threshold) return;

  // Retrieve decrypted Google OAuth token via Supabase (Edge compatible fetch)
  const token = await getValidGoogleToken(userId);

  if (confidenceScore >= 90) {
    // High confidence: Execute autonomous defense
    await blockCalendarTime(userId, token);
    await logAction(userId, 'block_created', 'Inserted 1-hr BioMesh Focus Guard due to critical stress spike.');
  } else {
    // Ambiguous confidence: Route to Human-in-the-Loop approval loop
    await requestManualApproval(userId, stressScore);
    await logAction(userId, 'manual_approval_requested', 'Stress elevated, but signal noisy. Sent push notification for manual calendar block approval.');
  }
}

async function blockCalendarTime(userId: string, accessToken: string) {
  const startTime = new Date();
  const endTime = new Date(startTime.getTime() + 60 * 60 * 1000); // 1 hour block

  const event = {
    summary: '🛡️ BioMesh Focus Guard',
    description: 'Autonomous time block generated by BioMesh Sync due to elevated physiological load.',
    start: { dateTime: startTime.toISOString() },
    end: { dateTime: endTime.toISOString() },
  };

  const res = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(event),
  });

  if (!res.ok) throw new Error('Failed to create calendar block');
}

async function requestManualApproval(userId: string, stressScore: number) {
  // In production: trigger a lightweight push notification or Slack/Teams ping to the user
  console.log(`[Human-in-the-Loop] Dispatching approval ping to User ${userId}. Stress: ${stressScore}`);
}

async function getValidGoogleToken(userId: string): Promise<string> {
  // Logic to fetch from `wearable_connections`, check expiry, and call Google OAuth refresh endpoint if needed.
  return "mock_valid_token"; 
}

function calculateConfidence(score: number): number {
  // Evaluates HRV variance against the stress score to prevent false positives.
  return 92; 
}

async function logAction(userId: string, actionType: string, description: string) {
  await supabase.from('calendar_actions_log').insert({
    user_id: userId,
    action_type: actionType,
    description: description
  });
}
